version: '3.8'

services:
 
  db:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: devopscase_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./devopscaseback
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./devopscaseback:/app
    working_dir: /app
    command: bash -c "bundle install && rails db:create db:migrate && rails server -b '0.0.0.0'"
    ports:
      - "3000:3000" 
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: devopscase_development
    depends_on:
      db:
        condition: service_healthy


 
  frontend:
    build:
      context: ./devopscasefront
      dockerfile: Dockerfile
    container_name: frontend
    user: "1000:1000"
    volumes:
      - ./devopscasefront:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3001:5174" 
    depends_on:
      - backend

volumes:
  mysql_data:
