pokemons = [
  { name: 'Bulbasaur', abilities: 'Overgrow, Chlorophyll' },
  { name: 'Ivysaur', abilities: 'Overgrow, Chlorophyll' },
  { name: 'Venusaur', abilities: 'Overgrow, Chlorophyll' },
  { name: 'Charmander', abilities: 'Blaze, Solar Power' },
  { name: 'Charmeleon', abilities: 'Blaze, Solar Power' },
  { name: 'Charizard', abilities: 'Blaze, Solar Power' },
  { name: 'Squirtle', abilities: 'Torrent, Rain Dish' },
  { name: 'Wartortle', abilities: 'Torrent, Rain Dish' },
  { name: 'Blastoise', abilities: 'Torrent, Rain Dish' },
  { name: 'Pidgey', abilities: 'Keen Eye, Tangled Feet' },
  { name: 'Pidgeotto', abilities: 'Keen Eye, Tangled Feet' },
  { name: 'Pidgeot', abilities: 'Keen Eye, Tangled Feet' },
  { name: 'Rattata', abilities: 'Run Away, Guts' },
  { name: 'Raticate', abilities: 'Run Away, Guts' },
  { name: 'Jigglypuff', abilities: 'Cute Charm, Competitive' },
  { name: 'Wigglytuff', abilities: 'Cute Charm, Competitive' },
  { name: 'Zubat', abilities: 'Inner Focus, Infiltrator' },
  { name: 'Golbat', abilities: 'Inner Focus, Infiltrator' },
  { name: 'Psyduck', abilities: 'Damp, Cloud Nine' },
  { name: 'Golduck', abilities: 'Damp, Cloud Nine' },
  { name: 'Machop', abilities: 'Guts, No Guard' },
  { name: 'Machoke', abilities: 'Guts, No Guard' },
  { name: 'Machamp', abilities: 'Guts, No Guard' },
  { name: 'Magnemite', abilities: 'Magnet Pull, Sturdy' },
  { name: 'Magneton', abilities: 'Magnet Pull, Sturdy' },
  { name: 'Growlithe', abilities: 'Intimidate, Justified' },
  { name: 'Arcanine', abilities: 'Intimidate, Justified' },
  { name: 'Poliwag', abilities: 'Water Absorb, Damp' },
  { name: 'Poliwhirl', abilities: 'Water Absorb, Damp' },
  { name: 'Politoed', abilities: 'Water Absorb, Damp' },
  { name: 'Abra', abilities: 'Synchronize, Inner Focus' },
  { name: 'Kadabra', abilities: 'Synchronize, Inner Focus' },
  { name: 'Alakazam', abilities: 'Synchronize, Inner Focus' },
  { name: 'Machop', abilities: 'Guts, No Guard' },
  { name: 'Bulbasaur', abilities: 'Overgrow, Chlorophyll' },
  { name: 'Onix', abilities: 'Rock Head, Sturdy' },
  { name: 'Drowzee', abilities: 'Insomnia, Forewarn' },
  { name: 'Hypno', abilities: 'Insomnia, Forewarn' },
  { name: 'Krabby', abilities: 'Hyper Cutter, Sheer Force' },
  { name: 'Kingler', abilities: 'Hyper Cutter, Sheer Force' },
  { name: 'Exeggcute', abilities: 'Chlorophyll, Harvest' },
  { name: 'Exeggutor', abilities: 'Chlorophyll, Harvest' }
]

pokemons.each do |pokemon|
  Pokemon.create!(name: pokemon[:name], abilities: pokemon[:abilities])
end
